export default function TableHead (){
return(
 <>
 <tr>
            <th>Cheez</th>
            <th>Cl</th>
            <th>Ca</th>
            <th>Fe</th>
            <th>Mg</th>
            <th>P</th>
            <th>K</th>
            <th>Na</th>
            <th>Zn</th>
            <th>Cu</th>
            <th>Mn</th>
            <th>Se</th>
        </tr>
 </>
);
}